"""Render a GitHub PR comment from a VulnSift triage report."""

from __future__ import annotations

from vulnsift.analytics import get_hotspots, get_priority_findings, summarize_report
from vulnsift.models import TriageReport

COMMENT_MARKER = "<!-- vulnsift-triage -->"


def render_github_comment(
    report: TriageReport,
    threshold: float | None = None,
) -> str:
    """Return GitHub-flavored Markdown for a PR comment summarising the triage report.

    Includes a hidden marker so the action can find and update existing comments.
    """
    entries = report.entries
    non_fp = [e for e in entries if not e.triage.is_likely_false_positive]
    fp_count = len(entries) - len(non_fp)
    max_risk = max((e.triage.risk_score for e in non_fp), default=0)
    summary = summarize_report(report)

    # Gate status
    if threshold is not None:
        gate_passed = max_risk < threshold
        badge = f"**Gate: {'PASSED' if gate_passed else 'FAILED'}** (threshold {threshold})"
        if gate_passed:
            badge_line = f":white_check_mark: {badge}"
        else:
            badge_line = f":x: {badge}"
    else:
        badge_line = ":information_source: **No gate threshold configured**"

    lines: list[str] = [
        COMMENT_MARKER,
        "## VulnSift Triage Summary",
        "",
        badge_line,
        "",
        "| Metric | Value |",
        "|--------|-------|",
        f"| Findings analysed | {len(entries)} |",
        f"| Highest risk score | {max_risk} |",
        f"| Likely false positives | {fp_count} |",
        f"| Actionable findings | {len(non_fp)} |",
        f"| Average actionable risk | {summary['average_risk']} |",
        (
            f"| Risk distribution | "
            f"high {summary['risk_bands']['high']} / "
            f"medium {summary['risk_bands']['medium']} / "
            f"low {summary['risk_bands']['low']} |"
        ),
        "",
    ]

    # Top findings table (up to 15)
    if non_fp:
        sorted_entries = sorted(non_fp, key=lambda e: -e.triage.risk_score)
        top = sorted_entries[:15]
        lines.append("<details>")
        lines.append(f"<summary><strong>Top findings ({len(non_fp)} actionable)</strong></summary>")
        lines.append("")
        lines.append("| Risk | Rule | Title | File | Line |")
        lines.append("|------|------|-------|------|------|")
        for e in top:
            risk = e.triage.risk_score
            if risk >= 7:
                risk_display = f"**{risk}** :red_circle:"
            elif risk >= 4:
                risk_display = f"{risk} :orange_circle:"
            else:
                risk_display = f"{risk} :green_circle:"
            title = e.finding.title[:60] + ("..." if len(e.finding.title) > 60 else "")
            file_path = e.finding.location.file_path or "-"
            line = str(e.finding.location.start_line or "-")
            lines.append(f"| {risk_display} | `{e.finding.rule_id}` | {title} | `{file_path}` | {line} |")
        if len(non_fp) > 15:
            lines.append(f"\n*... and {len(non_fp) - 15} more findings.*")
        lines.append("")
        lines.append("</details>")
        lines.append("")

    hotspots = get_hotspots(report, limit=5)
    if hotspots:
        lines.append("<details>")
        lines.append("<summary><strong>Riskiest files</strong></summary>")
        lines.append("")
        lines.append("| File | Findings | High risk | Max risk |")
        lines.append("|------|----------|-----------|----------|")
        for hotspot in hotspots:
            lines.append(
                f"| `{hotspot['file_path']}` | {hotspot['finding_count']} | "
                f"{hotspot['high_risk_count']} | {hotspot['max_risk']} |"
            )
        lines.append("")
        lines.append("</details>")
        lines.append("")

    # Top remediation actions
    remediation_entries = [e for e in non_fp if e.remediation and e.triage.risk_score >= 4]
    if remediation_entries:
        top_rem = get_priority_findings(report, limit=5, min_risk=4)
        lines.append("<details>")
        lines.append("<summary><strong>Immediate priorities</strong></summary>")
        lines.append("")
        lines.append("| Risk | Rule | File | Suggested fix |")
        lines.append("|------|------|------|---------------|")
        for item in top_rem:
            line = f":{item['line']}" if item["line"] else ""
            fix = item["remediation_title"] or "Review manually"
            lines.append(
                f"| {item['risk_score']} | `{item['rule_id']}` | "
                f"`{item['file_path']}{line}` | {fix} |"
            )
        lines.append("")
        lines.append("</details>")
        lines.append("")

    lines.append("---")
    lines.append("*Generated by [VulnSift](https://github.com/kirilurbonas/VulnSift)*")

    return "\n".join(lines) + "\n"
